// Generated by CoffeeScript 1.8.0
(function() {
  define(["clazzy/Clazzy"], function(Class) {
    'use strict';
    return Class("mizuhiki.MizuhikiMeta", null, null, {
      constructor: function() {
        this._attachPoints = {};
        this._attachEvents = {};
        this._attachIds = {};
        this._dataBindings = {};
        this._setterBindings = {};
        return this;
      }
    });
  });

}).call(this);

//# sourceMappingURL=MizuhikiMeta.js.map
