// Generated by CoffeeScript 1.8.0
(function() {
  define(["clazzy/Clazzy", "clazzy/abstraction/Lang"], function(Class, lang) {
    'use strict';
    return Class("mizuhiki.TemplatedObject", null, null, {
      __dependencies: ["IRenderer", "IRendererMeta"],
      templateString: "<div>Dummy</div>",
      constructor: function() {
        this.addModel({
          Id: null,
          AttachPoint: null
        });
        this.PreviousAttachPoint = null;
        this.PreviousId = null;
        this.domNode = null;
        this._started = false;
        this.startup();
        return this;
      },
      startup: function() {
        return this._started = true;
      },
      render: function() {
        return this.IRenderer.render(this);
      },
      destroy: function() {
        return this.IRenderer.destroy(this);
      }
    });
  });

}).call(this);

//# sourceMappingURL=TemplatedObject.js.map
