// Generated by CoffeeScript 1.8.0
(function() {
  define(["mizuhiki/tests/Mizuhiki", "mizuhiki/tests/abstraction/module", "mizuhiki/tests/SoyaMilk", "mizuhiki/tests/TemplatedObject"], 1);

}).call(this);

//# sourceMappingURL=module.js.map
