// Generated by CoffeeScript 1.8.0
(function() {
  define(["dojo/main", "util/doh/main", "mizuhiki/TemplatedObject"], function(dojo, doh, TemplatedObject) {
    return doh.register("mizuhiki.tests.TemplatedObject", [
      {
        name: "new_Class_propertiesCreated",
        setUp: function() {},
        runTest: function(t) {
          var obj;
          obj = new TemplatedObject();
          doh.assertTrue(obj.haz("AttachPoint"));
          doh.assertTrue(obj.haz("PreviousAttachPoint"));
          doh.assertTrue(obj.haz("PreviousId"));
          doh.assertTrue(obj.haz("domNode"));
          return doh.assertTrue(obj.haz("_started"));
        }
      }, {
        name: "render_null_callsIRendererRender",
        setUp: function() {
          return this.obj = new TemplatedObject();
        },
        runTest: function(t) {
          var IRendererCalled;
          IRendererCalled = false;
          this.obj.IRenderer = {
            render: function(obj) {
              return IRendererCalled = true;
            }
          };
          this.obj.render();
          return doh.assertTrue(IRendererCalled);
        }
      }, {
        name: "destroy_null_callsIRendererDestroy",
        setUp: function() {
          return this.obj = new TemplatedObject();
        },
        runTest: function(t) {
          var IRendererCalled;
          IRendererCalled = false;
          this.obj.IRenderer = {
            destroy: function(obj) {
              return IRendererCalled = true;
            }
          };
          this.obj.destroy();
          return doh.assertTrue(IRendererCalled);
        }
      }
    ]);
  });

}).call(this);

//# sourceMappingURL=TemplatedObject.js.map
